/** 全局可调常量（后台 / content script 共用） */
const TgFbConfig = {
  FB_DELIVERY_TTL_MS: 3 * 60 * 1000,
  FB_SESSION_TTL_MS: 8 * 60 * 1000,
  MAX_QUEUE_FAILURES: 6,
  MAX_TARGET_FAILURES: 3,
  MAX_FB_TARGETS: 10,
  MAX_FORWARD_LOG: 50,
  INTER_GROUP_SEND_DELAY_MS: 2000,
  INTER_GROUP_AUTO_DELAY_MS: 400,
  TG_WAKE_INTERVAL_MS: 12000,
  IMAGE_FETCH_TIMEOUT_BASE_MS: 4000,
  IMAGE_FETCH_TIMEOUT_PER_SLOT_MS: 3500,
  MANUAL_IMAGE_FETCH_TIMEOUT_BASE_MS: 2000,
  MANUAL_IMAGE_FETCH_TIMEOUT_PER_SLOT_MS: 2000,
};

if (typeof globalThis !== "undefined") {
  globalThis.TgFbConfig = TgFbConfig;
}
