/** 全局可调常量（后台 / content script 共用） */
const TgFbConfig = {
  FB_DELIVERY_TTL_MS: 3 * 60 * 1000,
  FB_SESSION_TTL_MS: 8 * 60 * 1000,
  MAX_QUEUE_FAILURES: 6,
  MAX_TARGET_FAILURES: 3,
  MAX_FB_TARGETS: 10,
  MAX_FORWARD_LOG: 50,
  /** 优化：缩短群组间转发延迟 */
  INTER_GROUP_SEND_DELAY_MS: 1000,
  INTER_GROUP_AUTO_DELAY_MS: 200,
  /** 优化：缩短后台唤醒间隔 */
  TG_WAKE_INTERVAL_MS: 30000,
  /** 优化：缩短图片抓取超时，提升响应速度 */
  IMAGE_FETCH_TIMEOUT_BASE_MS: 2000,
  IMAGE_FETCH_TIMEOUT_PER_SLOT_MS: 1500,
  MANUAL_IMAGE_FETCH_TIMEOUT_BASE_MS: 1500,
  MANUAL_IMAGE_FETCH_TIMEOUT_PER_SLOT_MS: 1500,
  MAX_FILTER_RULE_LENGTH: 200,
  MAX_REGEX_PATTERN_LENGTH: 120,
  MAX_FORWARD_TEXT_LENGTH: 12000,
};

if (typeof globalThis !== "undefined") {
  globalThis.TgFbConfig = TgFbConfig;
}
